// generated by scripts/generate-builtin-assets.ts
import prompt_0 from "./prompts/builtin/CHALLENGE_PLANNER.md" with { type: "file" }
import prompt_1 from "./prompts/builtin/ctf-pwn-solver.md" with { type: "file" }
import prompt_2 from "./prompts/builtin/ctf-web-solver.md" with { type: "file" }
import skill_0 from "./skills/builtin/agent-browser/SKILL.md" with { type: "file" }
import skill_1 from "./skills/builtin/agent-browser/references/authentication.md" with { type: "file" }
import skill_2 from "./skills/builtin/agent-browser/references/commands.md" with { type: "file" }
import skill_3 from "./skills/builtin/agent-browser/references/profiling.md" with { type: "file" }
import skill_4 from "./skills/builtin/agent-browser/references/proxy-support.md" with { type: "file" }
import skill_5 from "./skills/builtin/agent-browser/references/session-management.md" with { type: "file" }
import skill_6 from "./skills/builtin/agent-browser/references/snapshot-refs.md" with { type: "file" }
import skill_7 from "./skills/builtin/agent-browser/references/video-recording.md" with { type: "file" }
import skill_8 from "./skills/builtin/agent-browser/templates/authenticated-session.sh" with { type: "file" }
import skill_9 from "./skills/builtin/agent-browser/templates/capture-workflow.sh" with { type: "file" }
import skill_10 from "./skills/builtin/agent-browser/templates/form-automation.sh" with { type: "file" }
import skill_11 from "./skills/builtin/ctf-pwn/SKILL.md" with { type: "file" }
import skill_12 from "./skills/builtin/ctf-web/SKILL.md" with { type: "file" }
import skill_13 from "./skills/builtin/ffuf-skill/SKILL.md" with { type: "file" }
import skill_14 from "./skills/builtin/ffuf-skill/references/ffuf-web-params.md" with { type: "file" }
import skill_15 from "./skills/builtin/fuzz-dicts-skills/SKILL.md" with { type: "file" }
import skill_16 from "./skills/builtin/fuzz-dicts-skills/XXEDicts/README.MD" with { type: "file" }
import skill_17 from "./skills/builtin/fuzz-dicts-skills/apiDict/api.txt" with { type: "file" }
import skill_18 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/README.md" with { type: "file" }
import skill_19 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/dict/default.txt" with { type: "file" }
import skill_20 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf-wscan/dict/ext.txt" with { type: "file" }
import skill_21 from "./skills/builtin/fuzz-dicts-skills/ctfDict/ctf.txt" with { type: "file" }
import skill_22 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/Filenames_or_Directories_All.txt" with { type: "file" }
import skill_23 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/admin变种.txt" with { type: "file" }
import skill_24 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/asp/top30000.txt" with { type: "file" }
import skill_25 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/dicc.txt" with { type: "file" }
import skill_26 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/en_dirctories_all.txt" with { type: "file" }
import skill_27 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/fileName10000.txt" with { type: "file" }
import skill_28 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/jsp/top100.txt" with { type: "file" }
import skill_29 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/php/phpFileName.txt" with { type: "file" }
import skill_30 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/php/top3000.txt" with { type: "file" }
import skill_31 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/top7000.txt" with { type: "file" }
import skill_32 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vulns.txt" with { type: "file" }
import skill_33 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/LDAP.txt" with { type: "file" }
import skill_34 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/Traversal.txt" with { type: "file" }
import skill_35 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/XML.txt" with { type: "file" }
import skill_36 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/XXEExploit.txt" with { type: "file" }
import skill_37 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/all.txt" with { type: "file" }
import skill_38 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/apache.txt" with { type: "file" }
import skill_39 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/cgis.txt" with { type: "file" }
import skill_40 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/coldfusion.txt" with { type: "file" }
import skill_41 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/domino.txt" with { type: "file" }
import skill_42 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/fatwire.txt" with { type: "file" }
import skill_43 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/fatwire_pagenames.txt" with { type: "file" }
import skill_44 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/frontpage.txt" with { type: "file" }
import skill_45 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/iis.txt" with { type: "file" }
import skill_46 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/iplanet.txt" with { type: "file" }
import skill_47 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/jrun.txt" with { type: "file" }
import skill_48 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/netware.txt" with { type: "file" }
import skill_49 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/oracle9i.txt" with { type: "file" }
import skill_50 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/sharepoint.txt" with { type: "file" }
import skill_51 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/sunas.txt" with { type: "file" }
import skill_52 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/tests.txt" with { type: "file" }
import skill_53 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/tomcat.txt" with { type: "file" }
import skill_54 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/vignette.txt" with { type: "file" }
import skill_55 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/weblogic.txt" with { type: "file" }
import skill_56 from "./skills/builtin/fuzz-dicts-skills/directoryDicts/vuls/websphere.txt" with { type: "file" }
import skill_57 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/README.md" with { type: "file" }
import skill_58 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/burpXssPayload.txt" with { type: "file" }
import skill_59 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/easyXssPayload.txt" with { type: "file" }
import skill_60 from "./skills/builtin/fuzz-dicts-skills/easyXssPayload/markdown-xss-payload.txt" with { type: "file" }
import skill_61 from "./skills/builtin/fuzz-dicts-skills/js/jsFileDict.txt" with { type: "file" }
import skill_62 from "./skills/builtin/fuzz-dicts-skills/paramDict/AllParam.txt" with { type: "file" }
import skill_63 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/CHANGELOG.md" with { type: "file" }
import skill_64 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/README.md" with { type: "file" }
import skill_65 from "./skills/builtin/fuzz-dicts-skills/paramDict/Arjun/db/params.txt" with { type: "file" }
import skill_66 from "./skills/builtin/fuzz-dicts-skills/paramDict/burp.txt" with { type: "file" }
import skill_67 from "./skills/builtin/fuzz-dicts-skills/paramDict/dir.txt" with { type: "file" }
import skill_68 from "./skills/builtin/fuzz-dicts-skills/paramDict/js.txt" with { type: "file" }
import skill_69 from "./skills/builtin/fuzz-dicts-skills/paramDict/parameter.txt" with { type: "file" }
import skill_70 from "./skills/builtin/fuzz-dicts-skills/paramDict/php.txt" with { type: "file" }
import skill_71 from "./skills/builtin/fuzz-dicts-skills/paramDict/vars.txt" with { type: "file" }
import skill_72 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/GhostScript-Rce.txt" with { type: "file" }
import skill_73 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Imagemagick-rce.txt" with { type: "file" }
import skill_74 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/RCE-filter-and-WAF-Bypass.txt" with { type: "file" }
import skill_75 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/README.md" with { type: "file" }
import skill_76 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Top-46-RCE-Parameters.txt" with { type: "file" }
import skill_77 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Unix-Commond-Inject-Payload-List.txt" with { type: "file" }
import skill_78 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/Windows-Commond-Inject-Payload-List.txt" with { type: "file" }
import skill_79 from "./skills/builtin/fuzz-dicts-skills/rcePayloads/rce-when-all-dangerous-characters-are-escaped.txt" with { type: "file" }
import skill_80 from "./skills/builtin/fuzz-dicts-skills/references/navigation.md" with { type: "file" }
import skill_81 from "./skills/builtin/fuzz-dicts-skills/references/tool-playbooks.md" with { type: "file" }
import skill_82 from "./skills/builtin/fuzz-dicts-skills/spring/spring-configuration-metadata.txt" with { type: "file" }
import skill_83 from "./skills/builtin/fuzz-dicts-skills/sqlDict/sql.txt" with { type: "file" }
import skill_84 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/aix_etc.txt" with { type: "file" }
import skill_85 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/centsOS_etc.txt" with { type: "file" }
import skill_86 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/config.txt" with { type: "file" }
import skill_87 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/lfi-scanner.txt" with { type: "file" }
import skill_88 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/linux常见路径.txt" with { type: "file" }
import skill_89 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/log.txt" with { type: "file" }
import skill_90 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/proc.txt" with { type: "file" }
import skill_91 from "./skills/builtin/fuzz-dicts-skills/ssrfDicts/ssrf.txt" with { type: "file" }
import skill_92 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/all_upload_fuzz.txt" with { type: "file" }
import skill_93 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/apache_upload_fuzz.txt" with { type: "file" }
import skill_94 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/asp_upload_fuzz.txt" with { type: "file" }
import skill_95 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/iis_upload_fuzz.txt" with { type: "file" }
import skill_96 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/jsp_upload_fuzz.txt" with { type: "file" }
import skill_97 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/linux_upload_fuzz.txt" with { type: "file" }
import skill_98 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/php_upload_fuzz.txt" with { type: "file" }
import skill_99 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/tomcat_upload_fuzz.txt" with { type: "file" }
import skill_100 from "./skills/builtin/fuzz-dicts-skills/uploadFileExtDicts/win_upload_fuzz.txt" with { type: "file" }
import skill_101 from "./skills/builtin/jwt-tool-skill/SKILL.md" with { type: "file" }
import skill_102 from "./skills/builtin/jwt-tool-skill/evals/evals.json" with { type: "file" }
import skill_103 from "./skills/builtin/jwt-tool-skill/references/command-recipes.md" with { type: "file" }
import skill_104 from "./skills/builtin/payload-research/SKILL.md" with { type: "file" }
import skill_105 from "./skills/builtin/php-payload-builder/SKILL.md" with { type: "file" }
import skill_106 from "./skills/builtin/tch-headless-skill/SKILL.md" with { type: "file" }
import skill_107 from "./skills/builtin/tch-headless-skill/evals/evals.json" with { type: "file" }
import runtime_0 from "../runtime/assets/Dockerfile" with { type: "file" }

export const BUILTIN_PROMPTS = {
    "CHALLENGE_PLANNER.md": prompt_0,
    "ctf-pwn-solver.md": prompt_1,
    "ctf-web-solver.md": prompt_2,
} as const

export const BUILTIN_SKILL_FILES = {
    "agent-browser/SKILL.md": skill_0,
    "agent-browser/references/authentication.md": skill_1,
    "agent-browser/references/commands.md": skill_2,
    "agent-browser/references/profiling.md": skill_3,
    "agent-browser/references/proxy-support.md": skill_4,
    "agent-browser/references/session-management.md": skill_5,
    "agent-browser/references/snapshot-refs.md": skill_6,
    "agent-browser/references/video-recording.md": skill_7,
    "agent-browser/templates/authenticated-session.sh": skill_8,
    "agent-browser/templates/capture-workflow.sh": skill_9,
    "agent-browser/templates/form-automation.sh": skill_10,
    "ctf-pwn/SKILL.md": skill_11,
    "ctf-web/SKILL.md": skill_12,
    "ffuf-skill/SKILL.md": skill_13,
    "ffuf-skill/references/ffuf-web-params.md": skill_14,
    "fuzz-dicts-skills/SKILL.md": skill_15,
    "fuzz-dicts-skills/XXEDicts/README.MD": skill_16,
    "fuzz-dicts-skills/apiDict/api.txt": skill_17,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/README.md": skill_18,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/dict/default.txt": skill_19,
    "fuzz-dicts-skills/ctfDict/ctf-wscan/dict/ext.txt": skill_20,
    "fuzz-dicts-skills/ctfDict/ctf.txt": skill_21,
    "fuzz-dicts-skills/directoryDicts/Filenames_or_Directories_All.txt": skill_22,
    "fuzz-dicts-skills/directoryDicts/admin变种.txt": skill_23,
    "fuzz-dicts-skills/directoryDicts/asp/top30000.txt": skill_24,
    "fuzz-dicts-skills/directoryDicts/dicc.txt": skill_25,
    "fuzz-dicts-skills/directoryDicts/en_dirctories_all.txt": skill_26,
    "fuzz-dicts-skills/directoryDicts/fileName10000.txt": skill_27,
    "fuzz-dicts-skills/directoryDicts/jsp/top100.txt": skill_28,
    "fuzz-dicts-skills/directoryDicts/php/phpFileName.txt": skill_29,
    "fuzz-dicts-skills/directoryDicts/php/top3000.txt": skill_30,
    "fuzz-dicts-skills/directoryDicts/top7000.txt": skill_31,
    "fuzz-dicts-skills/directoryDicts/vulns.txt": skill_32,
    "fuzz-dicts-skills/directoryDicts/vuls/LDAP.txt": skill_33,
    "fuzz-dicts-skills/directoryDicts/vuls/Traversal.txt": skill_34,
    "fuzz-dicts-skills/directoryDicts/vuls/XML.txt": skill_35,
    "fuzz-dicts-skills/directoryDicts/vuls/XXEExploit.txt": skill_36,
    "fuzz-dicts-skills/directoryDicts/vuls/all.txt": skill_37,
    "fuzz-dicts-skills/directoryDicts/vuls/apache.txt": skill_38,
    "fuzz-dicts-skills/directoryDicts/vuls/cgis.txt": skill_39,
    "fuzz-dicts-skills/directoryDicts/vuls/coldfusion.txt": skill_40,
    "fuzz-dicts-skills/directoryDicts/vuls/domino.txt": skill_41,
    "fuzz-dicts-skills/directoryDicts/vuls/fatwire.txt": skill_42,
    "fuzz-dicts-skills/directoryDicts/vuls/fatwire_pagenames.txt": skill_43,
    "fuzz-dicts-skills/directoryDicts/vuls/frontpage.txt": skill_44,
    "fuzz-dicts-skills/directoryDicts/vuls/iis.txt": skill_45,
    "fuzz-dicts-skills/directoryDicts/vuls/iplanet.txt": skill_46,
    "fuzz-dicts-skills/directoryDicts/vuls/jrun.txt": skill_47,
    "fuzz-dicts-skills/directoryDicts/vuls/netware.txt": skill_48,
    "fuzz-dicts-skills/directoryDicts/vuls/oracle9i.txt": skill_49,
    "fuzz-dicts-skills/directoryDicts/vuls/sharepoint.txt": skill_50,
    "fuzz-dicts-skills/directoryDicts/vuls/sunas.txt": skill_51,
    "fuzz-dicts-skills/directoryDicts/vuls/tests.txt": skill_52,
    "fuzz-dicts-skills/directoryDicts/vuls/tomcat.txt": skill_53,
    "fuzz-dicts-skills/directoryDicts/vuls/vignette.txt": skill_54,
    "fuzz-dicts-skills/directoryDicts/vuls/weblogic.txt": skill_55,
    "fuzz-dicts-skills/directoryDicts/vuls/websphere.txt": skill_56,
    "fuzz-dicts-skills/easyXssPayload/README.md": skill_57,
    "fuzz-dicts-skills/easyXssPayload/burpXssPayload.txt": skill_58,
    "fuzz-dicts-skills/easyXssPayload/easyXssPayload.txt": skill_59,
    "fuzz-dicts-skills/easyXssPayload/markdown-xss-payload.txt": skill_60,
    "fuzz-dicts-skills/js/jsFileDict.txt": skill_61,
    "fuzz-dicts-skills/paramDict/AllParam.txt": skill_62,
    "fuzz-dicts-skills/paramDict/Arjun/CHANGELOG.md": skill_63,
    "fuzz-dicts-skills/paramDict/Arjun/README.md": skill_64,
    "fuzz-dicts-skills/paramDict/Arjun/db/params.txt": skill_65,
    "fuzz-dicts-skills/paramDict/burp.txt": skill_66,
    "fuzz-dicts-skills/paramDict/dir.txt": skill_67,
    "fuzz-dicts-skills/paramDict/js.txt": skill_68,
    "fuzz-dicts-skills/paramDict/parameter.txt": skill_69,
    "fuzz-dicts-skills/paramDict/php.txt": skill_70,
    "fuzz-dicts-skills/paramDict/vars.txt": skill_71,
    "fuzz-dicts-skills/rcePayloads/GhostScript-Rce.txt": skill_72,
    "fuzz-dicts-skills/rcePayloads/Imagemagick-rce.txt": skill_73,
    "fuzz-dicts-skills/rcePayloads/RCE-filter-and-WAF-Bypass.txt": skill_74,
    "fuzz-dicts-skills/rcePayloads/README.md": skill_75,
    "fuzz-dicts-skills/rcePayloads/Top-46-RCE-Parameters.txt": skill_76,
    "fuzz-dicts-skills/rcePayloads/Unix-Commond-Inject-Payload-List.txt": skill_77,
    "fuzz-dicts-skills/rcePayloads/Windows-Commond-Inject-Payload-List.txt": skill_78,
    "fuzz-dicts-skills/rcePayloads/rce-when-all-dangerous-characters-are-escaped.txt": skill_79,
    "fuzz-dicts-skills/references/navigation.md": skill_80,
    "fuzz-dicts-skills/references/tool-playbooks.md": skill_81,
    "fuzz-dicts-skills/spring/spring-configuration-metadata.txt": skill_82,
    "fuzz-dicts-skills/sqlDict/sql.txt": skill_83,
    "fuzz-dicts-skills/ssrfDicts/aix_etc.txt": skill_84,
    "fuzz-dicts-skills/ssrfDicts/centsOS_etc.txt": skill_85,
    "fuzz-dicts-skills/ssrfDicts/config.txt": skill_86,
    "fuzz-dicts-skills/ssrfDicts/lfi-scanner.txt": skill_87,
    "fuzz-dicts-skills/ssrfDicts/linux常见路径.txt": skill_88,
    "fuzz-dicts-skills/ssrfDicts/log.txt": skill_89,
    "fuzz-dicts-skills/ssrfDicts/proc.txt": skill_90,
    "fuzz-dicts-skills/ssrfDicts/ssrf.txt": skill_91,
    "fuzz-dicts-skills/uploadFileExtDicts/all_upload_fuzz.txt": skill_92,
    "fuzz-dicts-skills/uploadFileExtDicts/apache_upload_fuzz.txt": skill_93,
    "fuzz-dicts-skills/uploadFileExtDicts/asp_upload_fuzz.txt": skill_94,
    "fuzz-dicts-skills/uploadFileExtDicts/iis_upload_fuzz.txt": skill_95,
    "fuzz-dicts-skills/uploadFileExtDicts/jsp_upload_fuzz.txt": skill_96,
    "fuzz-dicts-skills/uploadFileExtDicts/linux_upload_fuzz.txt": skill_97,
    "fuzz-dicts-skills/uploadFileExtDicts/php_upload_fuzz.txt": skill_98,
    "fuzz-dicts-skills/uploadFileExtDicts/tomcat_upload_fuzz.txt": skill_99,
    "fuzz-dicts-skills/uploadFileExtDicts/win_upload_fuzz.txt": skill_100,
    "jwt-tool-skill/SKILL.md": skill_101,
    "jwt-tool-skill/evals/evals.json": skill_102,
    "jwt-tool-skill/references/command-recipes.md": skill_103,
    "payload-research/SKILL.md": skill_104,
    "php-payload-builder/SKILL.md": skill_105,
    "tch-headless-skill/SKILL.md": skill_106,
    "tch-headless-skill/evals/evals.json": skill_107,
} as const

export const RUNTIME_ASSET_FILES = {
    "Dockerfile": runtime_0,
} as const
