import { readdirSync, statSync } from "fs"
import { basename, dirname, extname, relative, resolve } from "path"

const projectRoot = resolve(import.meta.dir, "..")
const configDir = resolve(projectRoot, "packages/core/src/config")
const promptsBuiltinDir = resolve(configDir, "prompts/builtin")
const skillsBuiltinDir = resolve(configDir, "skills/builtin")
const runtimeDir = resolve(projectRoot, "packages/core/src/runtime")
const runtimeAssetsDir = resolve(runtimeDir, "assets")
const outputPath = resolve(configDir, "builtin-assets.generated.ts")

const BUILTIN_PROMPT_ALLOWLIST = new Set([
    "CHALLENGE_PLANNER.md",
    "ctf-pwn-solver.md",
    "ctf-web-solver.md",
])

const BUILTIN_SKILL_ALLOWLIST = new Set([
    "agent-browser",
    "ctf-pwn",
    "ctf-web",
    "ffuf-skill",
    "fuzz-dicts-skills",
    "jwt-tool-skill",
    "payload-research",
    "php-payload-builder",
    "tch-headless-skill",
])

const FUZZ_DICTS_TOP_LEVEL_ALLOWLIST = new Set([
    "XXEDicts",
    "apiDict",
    "ctfDict",
    "directoryDicts",
    "easyXssPayload",
    "js",
    "paramDict",
    "rcePayloads",
    "references",
    "spring",
    "sqlDict",
    "ssrfDicts",
    "uploadFileExtDicts",
])

function collectFiles(dir: string): string[] {
    const files: string[] = []

    function walk(currentDir: string) {
        for (const entry of readdirSync(currentDir)) {
            if (entry.startsWith(".")) continue
            const fullPath = resolve(currentDir, entry)
            const stat = statSync(fullPath)
            if (stat.isDirectory()) {
                walk(fullPath)
            } else {
                files.push(relative(configDir, fullPath).replaceAll("\\", "/"))
            }
        }
    }

    walk(dir)
    return files.sort()
}

function escapeIdentifier(value: string): string {
    return value.replace(/[^a-zA-Z0-9_]/g, "_")
}

function shouldIncludeBuiltinPromptFile(file: string): boolean {
    const prefix = "prompts/builtin/"
    if (!file.startsWith(prefix) || !file.endsWith(".md")) return false
    return BUILTIN_PROMPT_ALLOWLIST.has(file.slice(prefix.length))
}

function shouldIncludeFuzzDictsFile(file: string): boolean {
    const relativePath = file.slice("skills/builtin/fuzz-dicts-skills/".length)
    if (relativePath === "SKILL.md") return true
    const [topLevel] = relativePath.split("/")
    return Boolean(topLevel && FUZZ_DICTS_TOP_LEVEL_ALLOWLIST.has(topLevel))
}

function shouldIncludeBuiltinSkillFile(file: string): boolean {
    const prefix = "skills/builtin/"
    if (!file.startsWith(prefix)) return false
    const [skillDir] = file.slice(prefix.length).split("/")
    if (!skillDir || !BUILTIN_SKILL_ALLOWLIST.has(skillDir)) return false
    if (skillDir === "fuzz-dicts-skills" && !shouldIncludeFuzzDictsFile(file)) return false

    const ext = extname(file).toLowerCase()
    if (ext === ".md" || ext === ".txt" || ext === ".json" || ext === ".sh" || ext === ".yaml" || ext === ".yml") return true
    if (!ext && file.includes("/scripts/")) return true
    return basename(file) === "SKILL"
}

export async function generateBuiltinAssets(): Promise<void> {
    const promptFiles = collectFiles(promptsBuiltinDir).filter(shouldIncludeBuiltinPromptFile)
    const skillFiles = collectFiles(skillsBuiltinDir).filter(shouldIncludeBuiltinSkillFile)
    const runtimeFiles = collectFiles(runtimeAssetsDir).filter((file) => basename(file) !== "tch-agent-linux-x64")

    const lines: string[] = ["// generated by scripts/generate-builtin-assets.ts"]

    for (const [index, file] of promptFiles.entries()) {
        lines.push(`import prompt_${escapeIdentifier(String(index))} from "./${file}" with { type: "file" }`)
    }

    for (const [index, file] of skillFiles.entries()) {
        lines.push(`import skill_${escapeIdentifier(String(index))} from "./${file}" with { type: "file" }`)
    }

    for (const [index, file] of runtimeFiles.entries()) {
        lines.push(`import runtime_${escapeIdentifier(String(index))} from "${file}" with { type: "file" }`)
    }

    lines.push("")
    lines.push("export const BUILTIN_PROMPTS = {")
    for (const [index, file] of promptFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("prompts/builtin/".length))}: prompt_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")
    lines.push("export const BUILTIN_SKILL_FILES = {")
    for (const [index, file] of skillFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("skills/builtin/".length))}: skill_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")
    lines.push("export const RUNTIME_ASSET_FILES = {")
    for (const [index, file] of runtimeFiles.entries()) {
        lines.push(`    ${JSON.stringify(file.slice("../runtime/assets/".length))}: runtime_${escapeIdentifier(String(index))},`)
    }
    lines.push("} as const")
    lines.push("")

    await Bun.write(outputPath, lines.join("\n"))
}

if (import.meta.path === Bun.main) {
    await generateBuiltinAssets()
}
